// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp.Models;

public partial class Student
{
    public int StudentId { get; set; }

    public string StudName { get; set; }

    public int? StudAge { get; set; }

    public string StudEmail { get; set; }

    public string StudDepartment { get; set; }

    public string Skills { get; set; }

    public bool? IsActive { get; set; }
}